[package]
name = "trow"
version = "0.1.0"
authors = ["Adrian Mouat <adrian.mouat@container-solutions.com>", "Hamish Hutchings <hamish.hutchings@container-solutions.com>"]

[dependencies]
rust-crypto = "^0.2"
jwt = "^0.4"
rustc-serialize = "^0.3"

rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "b0f86dcba0629e1ab402c35e1ac2602348aad0d7", features = ["tls"] }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket", rev = "b0f86dcba0629e1ab402c35e1ac2602348aad0d7" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", rev = "b0f86dcba0629e1ab402c35e1ac2602348aad0d7" }

serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
uuid = { version = "^0.5", features = ["v4", "rustc-serialize"] }
log = "^0.3"
env_logger = "^0.4"
ctrlc = { version = "^3.0", features = ["termination"] }
hostname = "^0.1"

grpcio = "=0.2.3"
protobuf = "=1.4.5"

clap = "~2.29"

orset = "^0.2"

failure = "^0.1"
failure_derive = "^0.1"

trow-protobuf = { path = "./lib/protobuf" }
trow-backend = { path = "./lib/backend" }

#This is a rocket dependency, but we need a newer version with the p>q bugfix
ring ="^0.13"

[build-dependencies]

[dev-dependencies]
quickcheck = "^0.6"
assert_cli = "^0.5"
environment = "^0.1"
hyper = "^0.11"
rand = "^0.4"
reqwest = "^0.8"
